{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: argocd-cert-cronjob
  namespace: {{ $.Values.argocdNamespace| default .Release.Namespace }}
spec:
  schedule: {{ $.Values.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if  $.Values.podSecurityContext }}
          securityContext: 
{{ toYaml $.Values.podSecurityContext | indent 12 }}      
          {{- end }}
          serviceAccountName: argocd-cert-sa
          serviceAccount: argocd-cert-sa
          containers:
          - name: argocd-cert-cron
            image: {{ $.Values.image }}
            env:
              - name: devtronNamespace
                value: {{ $.Values.devtronNamespace| default .Release.Namespace }}
              - name: argocdNamespace
                value: {{ $.Values.argocdNamespace| default .Release.Namespace }}
              - name: clusterType
                value: {{ $.Values.clusterType | default "ENTERPRISE"  | quote }}
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash", "-c", "chmod +x argocd.sh && bash argocd.sh"]
            {{- if $.Values.containerSecurityContext }}
            securityContext: 
{{ toYaml $.Values.containerSecurityContext | indent 14 }}         
            {{- end}}
          restartPolicy: OnFailure
          
