name: argo-workflow
description: Chart to deploy argo-workflow
version: 0.1.6
apiVersion: v1
maintainers:
- email: pawan@devtron.ai
  name: Pawan
- email: devops@devtron.ai
  name: Devops-Team DEVTRON
