apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name  }}-secret
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database_credentials.db_password | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name  }}-configmap
data:
  DB_TYPE: {{ .Values.database_credentials.db_type | quote }}
  DB_HOST: {{ .Values.database_credentials.db_host | quote }}
  DB_PORT: {{ .Values.database_credentials.db_port | quote }}
  DB_USER_NAME: {{ .Values.database_credentials.db_user | quote }}