apiVersion: v1
appVersion: 3.0.0-pre
description: Clair is an open source project for the static analysis of vulnerabilities
  in application containers.
home: https://coreos.com/clair
icon: https://cloud.githubusercontent.com/assets/343539/21630811/c5081e5c-d202-11e6-92eb-919d5999c77a.png
maintainers:
- email: jimmy.zelinskie@coreos.com
  name: Jimmy Zelinskie
name: clair
sources:
- https://github.com/coreos/clair
version: 0.1.7
