apiVersion: {{ .Values.daemonsetapiversion }}
kind: DaemonSet
metadata:
  name: {{ template "coralogix-fluentd.name" . }}-daemonset
  namespace: kube-system
  labels:
    k8s-app: {{ template "coralogix-fluentd.fullname" . }}
    k8s-app-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: {{ template "coralogix-fluentd.fullname" . }}
  template:
    metadata:
      labels:
        k8s-app: {{ template "coralogix-fluentd.fullname" . }}
        k8s-app-version: {{ .Chart.AppVersion }}
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluentd-coralogix
        image: {{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}
        imagePullPolicy: {{ .Values.container.image.pullPolicy }}
        ports:
        - containerPort: 24224
          protocol: TCP
          name: fluentd
        - containerPort: 9880
          protocol: TCP
          name: http
        - containerPort: 5140
          protocol: UDP
          name: syslog
        - containerPort: 12201
          protocol: UDP
          name: graylog
        envFrom:
        - secretRef:
           name: {{ template "coralogix-fluentd.name" . }}-account-secrets
        resources:
{{ toYaml .Values.container.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: fluentd-config
          mountPath: /fluentd/etc/conf/kubernetes.conf
          subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: {{ template "coralogix-fluentd.name" . }}-configs
      {{- if .Values.rbac.create }}
      serviceAccount: {{ template "coralogix-fluentd.name" . }}-service-account
      serviceAccountName: {{ template "coralogix-fluentd.name" . }}-service-account
      {{- end }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
