apiVersion: v1
kind: Secret
metadata:
  name: twistlock-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  service-parameter: {{ .Values.service_parameter }}
  defender-ca.pem: {{ .Values.defender_ca_cert }}
  defender-client-cert.pem: {{ .Values.defender_client_cert }}
  defender-client-key.pem: {{ .Values.defender_client_key }}
{{- if .Values.old_defender_ca_cert }}
  defender-ca.pem.old: {{ .Values.old_defender_ca_cert }}
  defender-client-cert.pem.old: {{ .Values.old_defender_client_cert }}
  defender-client-key.pem.old: {{ .Values.old_defender_client_key }}
{{- end}}
  admission-cert.pem: {{ .Values.admission_cert }}
  admission-key.pem: {{ .Values.admission_key }}
{{if .Values.access_ca}}
  access-ca.pem: {{ .Values.access_ca }}
{{- end}}