apiVersion: v1
kind: ServiceAccount # Service Account is used for managing security context constraints policies in Openshift (SCC)
metadata:
  name: twistlock-service
  namespace: {{ .Values.namespace }}
{{- if .Values.role_arn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.role_arn }}
{{- end}}
secrets:
- name: twistlock-secrets