name: winter-soldier
description: Helm chart to deploy winter-soldier. Winter soldier can be used for scheduled cleaning up of Kubernetes resources and scaledown kubernetes workloads according to user defined time of the day and conditions.
version: 0.10.0
apiVersion: v1
appVersion: 0.1.0
maintainers:
- email: devops@devtron.ai
  name: Devtron Devops Team
- email: ajay@devtron.ai
  name: Ajay
