configs:
  REPO_NAME: ""
  SVN_REPO_URL: ""
  SVN_USERNAME: ""
  # Add git remote url without https://
  GIT_REMOTE_URL: ""
  GIT_REMOTE_USERNAME: ""
  # If your branches are on a location other than default branches/, then mention that
  # for e.g. branch/* if branches are available in branch directory
  BRANCHES: ""

secrets:
  SVN_PASSWORD: ""
  GIT_REMOTE_TOKEN: ""

# If you want to sync only few branches and don't want to sync all branches, then mention those branches here
CUSTOM_BRANCHES_TO_SYNC: []

image: "quay.io/devtron/svn-git-sync:v6"
imagePullPolicy: "IfNotPresent"

podLabels: {}
podAnnotations: {}

persistence:
  enabled: true
  size: "2Gi"
  storageClass: "default"