name: devtron-in-clustercd
description: Helm chart to deploy devtron-in-clustercd to run pre and post deployment in application/target cluster.
version: 0.10.2
appVersion: 0.1.0
apiVersion: v1
maintainers:
- email: devops@devtron.ai
  name: Devtron Devops Team
- email: ajay@devtron.ai
  name: Ajay
