# AWS credentials configuration
aws:
  accessKey: "your-aws-access-key"          # AWS Access Key ID of IAM role for authentication
  secretKey: "your-aws-secret-key"          # AWS Secret Access Key of IAM role for authentication
  region: "your-aws-region"                 # AWS region where your resources are located
  roleArn: "your-aws-role-arn"              # ARN of the AWS role to assume for getting temporary credentials
  sessionName: "your-session-name"          # Session name for the assumed role

# Kubernetes configuration
kubernetes:
  secretName: "your-secret-name"            # Name of the Kubernetes secret to create or update with ECR credentials

# ECR (Elastic Container Registry) configuration
ecr:
  account: "your-aws-account"               # AWS account ID where your ECR is located
  region: "your-ecr-region"                 # AWS region of your ECR

# CronJob configuration
cronjob:
  schedule: "0 */12 * * *"                  # Cron schedule for the job to run (every 12 hours)

# ServiceAccount configuration
serviceAccount:
  name: "renew-ecr-k8s-creds-sa"            # Name of the ServiceAccount to create or use
