apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-alertmanager
  labels:
    app: discord
spec:
  selector:
    matchLabels:
      app: discord
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: discord
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      containers:
        - name: discord
          image: {{ .Values.image }}
          ports:
            - name: discord
              containerPort: {{ .Values.container_port}}
              protocol: TCP
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $value.name }}
              value: {{ $value.value }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{ if $.Values.affinity }}
      affinity:
          {{ toYaml $.Values.affinity | indent 10 }}
          {{- end }}
